---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo
  
- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - spice-vdagent  
      - golang-go
      - feroxbuster
      - neo4j
      - rsyslog
      - ufw
      - dconf-cli
      - cargo
      - gnome-shell-extension-manager
      - oscanner
      - tnscmd10g
      - wkhtmltopdf
      - xsel
      - wine64
      - ipcalc
      - terminator
    state: latest
  become: true
  become_method: sudo
