---
- name: "Customizing Kali"
  hosts: localhost
  connection: local
  vars:
    burpsuite_user: kali
    burpsuite_edition: pro
    burpsuite_pro_license_key: "{{ lookup('file', '/mnt/hgfs/Lincense_files/Burp_Suite_Professional_License.txt') }}"
  roles:
    - role: "roles/install-tools"
    - role: "roles/configure-tmux"
    - role: "roles/customize-terminal"
    - role: "roles/customize-browser"
    - role: "roles/configure-logging"
    - role: chaosmail.sublime-text
    - role: gantsign.visual-studio-code
    - role: iesplin.burp_suite
      users:
        - username: "{{ ansible_user_id }}" 
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - DEVSENSE.phptools-vscode
            - snyk-security.snyk-vulnerability-scanner
            - esbenp.prettier-vscode
            - ms-vscode.powershell
            - ms-vscode.cpptools
              # - role: gantsign.oh-my-zsh
              #   users: 
              #     - username: "{{ ansible_user_id }}"
              #       oh_my_zsh:
              #         theme: gallois
              #         plugins:
              #           - git
              #         update_mode: reminder
              #         update_frequency: 3
              #         write_zshrc: false
         
