---
- name: "Customizing Kali"
  hosts: localhost
  connection: local
  vars_files:
    - /mnt/hgfs/License_files/secret_vars.yml

  roles:
    - role: "roles/install-tools"
    - role: "roles/configure-tmux"
    - role: "roles/customize-terminal"
    - role: "roles/customize-browser"
    - role: "roles/configure-logging"
    - role: gantsign.visual-studio-code
    - role: chaosmail.sublime-text
      users:
        - username: "{{ ansible_user_id }}" 
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - DEVSENSE.phptools-vscode
            - snyk-security.snyk-vulnerability-scanner
            - esbenp.prettier-vscode
            - GitHub.copilot
            - ms-vscode.powershell
            - ms-vscode.cpptools
    - role: "roles/customise-kali"
         
