---
- name: "Customizing Kali"
  hosts: localhost
  connection: local
  vars_files:
    - /mnt/hgfs/License_files/secret_vars.yml
  vars:
    burpsuite_user: kali
    burpsuite_edition: pro
    burpsuite_pro_license_key: "{{ burp_license }}"

# Removing burp suite installation for now due to licensing and activation issues.

  roles:
    - role: "roles/install-tools"
    - role: "roles/configure-tmux"
    - role: "roles/customize-terminal"
    - role: "roles/customize-browser"
    - role: "roles/configure-logging"
    #- role: iesplin.burp_suite
    - role: gantsign.visual-studio-code
    - role: chaosmail.sublime-text
      sublime_version: 3
      sublime_package_control: true
      sublime_packages:
        - 'https://github.com/skuroda/Sublime-AdvancedNewFile.git'
        - 'https://github.com/weslly/ColorPicker.git'
        - 'https://github.com/revolunet/sublimetext-markdown-preview'
        - 'https://github.com/randy3k/Terminus.git'
        - 'https://github.com/dzhibas/SublimePrettyJson.git'
        - 'https://github.com/jdavisclark/JsFormat.git'
        - 'https://github.com/molovo/sublime-zsh.git'
        - 'https://github.com/facelessuser/BracketHighlighter.git'
        - 'https://github.com/stevebasher/Split-Line-Sublime-Plugin.git'
        - 'https://github.com/kaste/Compare-Side-By-Side.git'
      users:
        - username: "{{ ansible_user_id }}" 
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - DEVSENSE.phptools-vscode
            - snyk-security.snyk-vulnerability-scanner
            - esbenp.prettier-vscode
            - GitHub.copilot
            - ms-vscode.powershell
            - ms-vscode.cpptools
              # - role: gantsign.oh-my-zsh
              #   users: 
              #     - username: "{{ ansible_user_id }}"
              #       oh_my_zsh:
              #         theme: gallois
              #         plugins:
              #           - git
              #         update_mode: reminder
              #         update_frequency: 3
              #         write_zshrc: false
         
